from __future__ import annotations

import json
from typing import Callable

from runtime_runner_finalize import finalize_runner_outputs  # type: ignore
from runtime_runner_context import RuntimeRunnerContext  # type: ignore
from runtime_session_flow import run_runtime_session  # type: ignore


def execute_runner_session(
    *,
    state,
    max_runs: int,
    target_load_limit: int,
    time_budget_min: int,
    retry_policy: str,
    run_started,
    scope_targets: list[str],
    preempt_in_curated: bool,
    queue_coordinator,
    log_event_fn,
    read_runtime_control_state_fn,
    read_runtime_owner_override_fn,
    read_runtime_aggression_override_fn,
    apply_runtime_overrides_fn,
    handle_post_run_actions_fn,
    prepare_curated_task_fn,
    prepare_runtime_task_fn,
    reprioritize_queues_fn,
    persist_recorded_run_fn,
    maybe_trigger_plan_regeneration_fn,
    execute_runtime_task_fn,
    resolve_main_loop_candidate_fn,
    record_run_fn,
    persist_live_summary_fn,
    normalize_runtime_task_fn,
    reconcile_active_plan_if_needed_fn,
    maybe_preempt_curated_entry_fn,
    dedup_key_fn,
    build_deduped_target_plan_fn,
    prepare_deps,
    propose_next_vector_fn,
    unpack_queued_task_fn,
    clamp_aggression_fn,
    capped_aggression_fn,
    run_curated_loop_fn,
    run_main_loop_fn,
    out_path,
    reports_dir,
    archive_root,
    campaign_validation,
    quality_telemetry,
    finalize_outputs_fn,
    flush_precheck_summary_fn,
    flush_dns_skip_summary_fn,
    flush_host_cooldown_summary_fn,
    flush_execution_gate_summary_fn,
    log_operation_fn,
):
    log_operation_fn('AUTO_CAMPAIGN', 'AUTO CAMPAIGN', 'start', actor='auto_campaign', note=f'max_runs={max_runs};target_load_limit={target_load_limit};time_budget_min={time_budget_min};workers=1;retry_policy={retry_policy}')
    runner_ctx = RuntimeRunnerContext(
        queue_coordinator=queue_coordinator,
        log_event_fn=log_event_fn,
        read_runtime_control_state_fn=read_runtime_control_state_fn,
        read_runtime_owner_override_fn=read_runtime_owner_override_fn,
        read_runtime_aggression_override_fn=read_runtime_aggression_override_fn,
        apply_runtime_overrides_fn=apply_runtime_overrides_fn,
        handle_post_run_actions_fn=handle_post_run_actions_fn,
        prepare_curated_task_fn=prepare_curated_task_fn,
        prepare_runtime_task_fn=prepare_runtime_task_fn,
        reprioritize_queues_fn=reprioritize_queues_fn,
        persist_recorded_run_fn=persist_recorded_run_fn,
        maybe_trigger_plan_regeneration_fn=maybe_trigger_plan_regeneration_fn,
        execute_runtime_task_fn=execute_runtime_task_fn,
        resolve_main_loop_candidate_fn=resolve_main_loop_candidate_fn,
        record_run_fn=record_run_fn,
        persist_live_summary_fn=persist_live_summary_fn,
    )
    run_runtime_session(
        state=state,
        max_runs=max_runs,
        target_load_limit=target_load_limit,
        time_budget_min=time_budget_min,
        scope_targets=scope_targets,
        normalize_runtime_task_fn=normalize_runtime_task_fn,
        reconcile_active_plan_if_needed_fn=reconcile_active_plan_if_needed_fn,
        runner_ctx=runner_ctx,
        maybe_preempt_curated_entry_fn=maybe_preempt_curated_entry_fn,
        dedup_key_fn=dedup_key_fn,
        build_deduped_target_plan_fn=build_deduped_target_plan_fn,
        prepare_deps=prepare_deps,
        execute_runtime_task_fn=execute_runtime_task_fn,
        propose_next_vector_fn=propose_next_vector_fn,
        unpack_queued_task_fn=unpack_queued_task_fn,
        clamp_aggression_fn=clamp_aggression_fn,
        capped_aggression_fn=capped_aggression_fn,
        run_curated_loop_fn=run_curated_loop_fn,
        run_main_loop_fn=run_main_loop_fn,
        log_event_fn=log_event_fn,
        preempt_in_curated=preempt_in_curated,
        run_started=run_started,
    )
    summary = finalize_runner_outputs(
        runs=state.runs,
        campaign_validation=campaign_validation,
        run_started=run_started,
        max_runs=max_runs,
        time_budget_min=time_budget_min,
        retry_policy=retry_policy,
        out_path=out_path,
        reports_dir=reports_dir,
        archive_root=archive_root,
        output_quality_telemetry=quality_telemetry,
        finalize_outputs_fn=finalize_outputs_fn,
        flush_precheck_summary_fn=flush_precheck_summary_fn,
        flush_dns_skip_summary_fn=flush_dns_skip_summary_fn,
        flush_host_cooldown_summary_fn=flush_host_cooldown_summary_fn,
        flush_execution_gate_summary_fn=flush_execution_gate_summary_fn,
        log_operation_fn=log_operation_fn,
        success=True,
    )
    return summary


def finalize_runner_exception(
    *,
    state,
    campaign_validation,
    run_started,
    max_runs: int,
    time_budget_min: int,
    retry_policy: str,
    out_path,
    reports_dir,
    archive_root,
    quality_telemetry,
    finalize_outputs_fn,
    flush_precheck_summary_fn,
    flush_dns_skip_summary_fn,
    flush_host_cooldown_summary_fn,
    flush_execution_gate_summary_fn,
    log_operation_fn,
    error: Exception,
) -> None:
    finalize_runner_outputs(
        runs=state.runs,
        campaign_validation=campaign_validation,
        run_started=run_started,
        max_runs=max_runs,
        time_budget_min=time_budget_min,
        retry_policy=retry_policy,
        out_path=out_path,
        reports_dir=reports_dir,
        archive_root=archive_root,
        output_quality_telemetry=quality_telemetry,
        finalize_outputs_fn=finalize_outputs_fn,
        flush_precheck_summary_fn=flush_precheck_summary_fn,
        flush_dns_skip_summary_fn=flush_dns_skip_summary_fn,
        flush_host_cooldown_summary_fn=flush_host_cooldown_summary_fn,
        flush_execution_gate_summary_fn=flush_execution_gate_summary_fn,
        log_operation_fn=log_operation_fn,
        success=False,
        error=error,
    )
