from __future__ import annotations

from typing import Callable

from runtime_runner_context import resolve_main_loop_selected  # type: ignore


def _read_runtime_control_state_fn(runner_ctx):
    fn = getattr(runner_ctx, 'read_runtime_control_state', None)
    return fn if callable(fn) else (lambda: {})


def run_runtime_session(
    *,
    state,
    max_runs: int,
    target_load_limit: int,
    time_budget_min: int,
    scope_targets: list[str],
    normalize_runtime_task_fn,
    reconcile_active_plan_if_needed_fn,
    runner_ctx,
    maybe_preempt_curated_entry_fn,
    dedup_key_fn,
    build_deduped_target_plan_fn,
    prepare_deps,
    execute_runtime_task_fn,
    propose_next_vector_fn,
    unpack_queued_task_fn,
    clamp_aggression_fn,
    capped_aggression_fn,
    run_curated_loop_fn,
    run_main_loop_fn,
    log_event_fn,
    preempt_in_curated: bool,
    run_started,
):
    read_runtime_control_state_fn = _read_runtime_control_state_fn(runner_ctx)
    state.last_heartbeat_ts, state.confirm_total, state.idx, _ = run_curated_loop_fn(
        curated_plan=state.curated_plan,
        max_runs=max_runs,
        run_started=run_started,
        time_budget_min=time_budget_min,
        target_load_limit=target_load_limit,
        runs=state.runs,
        normalize_runtime_task_fn=normalize_runtime_task_fn,
        reconcile_active_plan_if_needed_fn=reconcile_active_plan_if_needed_fn,
        log_event_fn=log_event_fn,
        refresh_runtime_overrides_fn=runner_ctx.refresh_runtime_overrides,
        owner_override_global=runner_ctx.read_runtime_owner_override_fn(default=False),
        last_override_state=runner_ctx.read_runtime_owner_override_fn(default=False),
        aggression_override_global=runner_ctx.read_runtime_aggression_override_fn(),
        last_aggression_override=runner_ctx.read_runtime_aggression_override_fn(),
        preempt_in_curated=preempt_in_curated,
        precision_queue=state.precision_queue,
        followup_queue=state.followup_queue,
        maybe_preempt_curated_entry_fn=maybe_preempt_curated_entry_fn,
        dequeue_next_task_fn=runner_ctx.dequeue_next_task,
        requeue_task_fn=runner_ctx.requeue_task,
        prepare_curated_task_fn=prepare_deps.prepare_curated_task_fn,
        build_execute_runtime_request_fn=prepare_deps.build_execute_runtime_request_fn,
        execute_runtime_task_fn=execute_runtime_task_fn,
        last_heartbeat_ts=state.last_heartbeat_ts,
        confirm_total=state.confirm_total,
        idx=state.idx,
        build_deduped_target_plan_fn=build_deduped_target_plan_fn,
        dedup_key_fn=dedup_key_fn,
        read_runtime_control_state_fn=read_runtime_control_state_fn,
    )
    state.last_heartbeat_ts, state.confirm_total, _ = run_main_loop_fn(
        max_runs=max_runs,
        runs=state.runs,
        run_started=run_started,
        time_budget_min=time_budget_min,
        reconcile_active_plan_if_needed_fn=reconcile_active_plan_if_needed_fn,
        log_event_fn=log_event_fn,
        refresh_runtime_overrides_fn=runner_ctx.refresh_runtime_overrides,
        owner_override_global=runner_ctx.read_runtime_owner_override_fn(default=False),
        last_override_state=runner_ctx.read_runtime_owner_override_fn(default=False),
        aggression_override_global=runner_ctx.read_runtime_aggression_override_fn(),
        last_aggression_override=runner_ctx.read_runtime_aggression_override_fn(),
        dequeue_next_task_fn=runner_ctx.dequeue_next_task,
        requeue_task_fn=runner_ctx.requeue_task,
        history=state.history,
        scope_targets=scope_targets,
        normalize_runtime_task_fn=normalize_runtime_task_fn,
        unpack_queued_task_fn=unpack_queued_task_fn,
        clamp_aggression_fn=clamp_aggression_fn,
        capped_aggression_fn=capped_aggression_fn,
        propose_next_vector_fn=propose_next_vector_fn,
        prepare_runtime_task_fn=prepare_deps.prepare_runtime_task_fn,
        build_execute_runtime_request_fn=prepare_deps.build_execute_runtime_request_fn,
        execute_runtime_task_fn=execute_runtime_task_fn,
        last_heartbeat_ts=state.last_heartbeat_ts,
        confirm_total=state.confirm_total,
        read_runtime_control_state_fn=read_runtime_control_state_fn,
        selected_error_record_fn=lambda owner_override_global_local, aggression_override_global_local, dequeue_next_task_fn, history_local, scope_targets_local, normalize_runtime_task_fn, unpack_queued_task_fn, clamp_aggression_fn, capped_aggression_fn, propose_next_vector_fn: resolve_main_loop_selected(
            ctx=runner_ctx,
            runs=state.runs,
            owner_override_global=owner_override_global_local,
            aggression_override_global=aggression_override_global_local,
            history=history_local,
            scope_targets=scope_targets_local,
            normalize_runtime_task_fn=normalize_runtime_task_fn,
            unpack_queued_task_fn=unpack_queued_task_fn,
            clamp_aggression_fn=clamp_aggression_fn,
            capped_aggression_fn=capped_aggression_fn,
            propose_next_vector_fn=propose_next_vector_fn,
        ),
    )
