from __future__ import annotations

from typing import Any, Callable, Dict


def run_post_run_actions(
    *,
    task: Dict[str, Any],
    result: Dict[str, Any],
    qual: Dict[str, Any],
    classification: str,
    auditor: str,
    engine_status: str,
    success_eval_status: str,
    summary_text: str,
    reason_code: str,
    target: str,
    objective: str,
    aggression: int,
    owner_auth: bool,
    owner_override: bool,
    mode: str,
    retry_counts: dict,
    retry_limit: int,
    followup_queue: list,
    followup_counts: dict,
    followup_recent: dict,
    max_followups_per_target: int,
    scheduled_keys: set,
    host_weak_count: dict,
    host_family_owner_gate: dict,
    confirm_counts: dict,
    confirm_recent: dict,
    confirm_total: int,
    confirm_class_counts: dict,
    max_confirm_jobs_per_target: int,
    max_confirm_jobs_total: int,
    max_confirm_jobs_per_class: int,
    confirm_job_cooldown_sec: int,
    quality_telemetry: dict,
    toggles: dict,
    promising: bool,
    signal_contract: Dict[str, Any] | None = None,
    runtime_decision: Dict[str, Any] | None = None,
    enqueue_followup_task_fn: Callable[[dict, bool], None] | None = None,
    quality_aware_followup_admission_hint_fn: Callable[[Dict[str, Any], Dict[str, Any] | None, Dict[str, Any] | None], Dict[str, Any]] | None = None,
    apply_post_run_admission_hint_fn: Callable[[Dict[str, Any] | None, Dict[str, Any] | None], Dict[str, Any]] | None = None,
    build_post_run_action_inputs_fn: Callable[..., Any] | None = None,
    apply_effective_decision_fn: Callable[..., tuple[int, dict]] | None = None,
) -> tuple[int, dict]:
    admission_hint = quality_aware_followup_admission_hint_fn(task, result, runtime_decision) if quality_aware_followup_admission_hint_fn else {}
    runtime_decision_local = apply_post_run_admission_hint_fn(runtime_decision, admission_hint) if apply_post_run_admission_hint_fn else dict(runtime_decision or {})
    action_inputs = build_post_run_action_inputs_fn(
        task=task,
        result=result,
        qual=qual,
        classification=classification,
        auditor=auditor,
        engine_status=engine_status,
        success_eval_status=success_eval_status,
        summary_text=summary_text,
        reason_code=reason_code,
        target=target,
        objective=objective,
        aggression=aggression,
        owner_auth=owner_auth,
        owner_override=owner_override,
        mode=mode,
        retry_counts=retry_counts,
        retry_limit=retry_limit,
        followup_queue=followup_queue,
        followup_counts=followup_counts,
        followup_recent=followup_recent,
        max_followups_per_target=max_followups_per_target,
        scheduled_keys=scheduled_keys,
        host_weak_count=host_weak_count,
        host_family_owner_gate=host_family_owner_gate,
        confirm_counts=confirm_counts,
        confirm_recent=confirm_recent,
        confirm_total=confirm_total,
        confirm_class_counts=confirm_class_counts,
        max_confirm_jobs_per_target=max_confirm_jobs_per_target,
        max_confirm_jobs_total=max_confirm_jobs_total,
        max_confirm_jobs_per_class=max_confirm_jobs_per_class,
        confirm_job_cooldown_sec=confirm_job_cooldown_sec,
        quality_telemetry=quality_telemetry,
        toggles=toggles,
        promising=promising,
        signal_contract=signal_contract,
        runtime_decision=runtime_decision_local,
        enqueue_followup_task_fn=enqueue_followup_task_fn,
    )
    return apply_effective_decision_fn(**vars(action_inputs)) if apply_effective_decision_fn else (confirm_total, {})
